--INSERT INTO Planes VALUES ('Boeing 747', 40);

--INSERT INTO Destinations VALUES ('Gothenburg', 'GBG');
--INSERT INTO Destinations VALUES ('London', 'LDN');
--INSERT INTO Destinations VALUES ('Stockholm', 'STH');
--INSERT INTO Destinations VALUES ('Berlin', 'BER');
--INSERT INTO Destinations VALUES ('Copenhagen', 'CPH');
--INSERT INTO Destinations VALUES ('Arrabury', 'ARR');
--INSERT INTO Destinations VALUES ('Lanzarote', 'LAN');
--INSERT INTO Destinations VALUES ('Djibouti City', 'JIB');
--INSERT INTO Destinations VALUES ('Johannesburg', 'JNB');
--INSERT INTO Destinations VALUES ('Fort Lauderdale', 'FLL');
--INSERT INTO Destinations VALUES ('Los Angeles', 'LAX');
--INSERT INTO Destinations VALUES ('New York City', 'JFK');
--INSERT INTO Destinations VALUES ('Washington, D.C.', 'DCA');
--INSERT INTO Destinations VALUES ('Buenos Aires', 'EZE');
--INSERT INTO Destinations VALUES ('São Paulo', 'CGH');
--INSERT INTO Destinations VALUES ('Bogotá', 'BOG');
--INSERT INTO Destinations VALUES ('Medellín', 'MDE');
--INSERT INTO Destinations VALUES ('Pyongyangk', 'FNJ');
--INSERT INTO Destinations VALUES ('Tokyo', 'NRT');
--INSERT INTO Destinations VALUES ('Beijing', 'PEK');
--INSERT INTO Destinations VALUES ('Shanghai', 'SHA');
--INSERT INTO Destinations VALUES ('Hong Kong', 'HKG');
--INSERT INTO Destinations VALUES ('Taipei', 'TSA');
--INSERT INTO Destinations VALUES ('Busan', 'PUS');
--INSERT INTO Destinations VALUES ('Seoul', 'GMP');
--INSERT INTO Destinations VALUES ('Delhi', 'DEL');
--INSERT INTO Destinations VALUES ('Kathmandu', 'KTM');
--INSERT INTO Destinations VALUES ('Jakarta', 'HLP');
--INSERT INTO Destinations VALUES ('Kuala Lumpur', 'KUL');
--INSERT INTO Destinations VALUES ('Manila', 'MNL');
--INSERT INTO Destinations VALUES ('Singapore', 'SIN');
--INSERT INTO Destinations VALUES ('Phuket', 'HKT');
--INSERT INTO Destinations VALUES ('Ho Chi Minh City', 'SGN');
--INSERT INTO Destinations VALUES ('Jeddah', 'JED');
--INSERT INTO Destinations VALUES ('Abu Dhabi', 'AUH');
--INSERT INTO Destinations VALUES ('Brussels', 'BRU');
--INSERT INTO Destinations VALUES ('Paris', 'CDG');
--INSERT INTO Destinations VALUES ('Dublin', 'DUB');
--INSERT INTO Destinations VALUES ('Lisbon', 'LIS');
--INSERT INTO Destinations VALUES ('Ibiza', 'IBZ');
--INSERT INTO Destinations VALUES ('Athens', 'ATH');
--INSERT INTO Destinations VALUES ('ROME', 'FCO');
--INSERT INTO Destinations VALUES ('Moscow', 'DME');
--INSERT INTO Destinations VALUES ('Helsinki', 'HEL');
--INSERT INTO Destinations VALUES ('Mars', 'MRS');


--INSERT INTO Flights VALUES (1, 'Gothenburg', 'London', '2021-06-21', '14:00', 'Boeing 747');
--INSERT INTO Flights VALUES (2, 'Stockholm', 'Berlin', '2021-06-25', '18:00', 'Boeing 747');
--INSERT INTO Flights VALUES (3, 'Copenhagen', 'Frankfurt', '2021-02-28', '11:00', 'Boeing 747');

INSERT INTO Seats VALUES (1, '1A', false);
INSERT INTO Seats VALUES (1, '1B', false);
INSERT INTO Seats VALUES (1, '1C', false);
INSERT INTO Seats VALUES (1, '1D', false);