--INSERT INTO Planes VALUES ('Boeing 747', 40);

--INSERT INTO Destinations VALUES ('Gothenburg', 'GBG');
--INSERT INTO Destinations VALUES ('London', 'LDN');
--INSERT INTO Destinations VALUES ('Stockholm', 'STH');
--INSERT INTO Destinations VALUES ('Berlin', 'BER');
--INSERT INTO Destinations VALUES ('Copenhagen', 'CPH');
INSERT INTO Destinations VALUES ('Arrabury', 'ARR');
INSERT INTO Destinations VALUES ('Lanzarote', 'LAN');
INSERT INTO Destinations VALUES ('Djibouti City', 'DJI');
INSERT INTO Destinations VALUES ('Johannesburg', 'JNB');
INSERT INTO Destinations VALUES ('Fort Lauderdale', 'FLL');
INSERT INTO Destinations VALUES ('Los Angeles', 'LAX');
INSERT INTO Destinations VALUES ('New York City', 'NYC');
INSERT INTO Destinations VALUES ('Washington, D.C.', 'WDC');
INSERT INTO Destinations VALUES ('Buenos Aires', 'BAI');
INSERT INTO Destinations VALUES ('Sao Paulo', 'SPA');
INSERT INTO Destinations VALUES ('Bogota', 'BOG');
INSERT INTO Destinations VALUES ('Medellin', 'MDE');
INSERT INTO Destinations VALUES ('Pyongyang', 'PYO');
INSERT INTO Destinations VALUES ('Tokyo', 'TOK');
INSERT INTO Destinations VALUES ('Beijing', 'BEI');
INSERT INTO Destinations VALUES ('Shanghai', 'SHA');
INSERT INTO Destinations VALUES ('Hong Kong', 'HKG');
INSERT INTO Destinations VALUES ('Taipei', 'TPI');
INSERT INTO Destinations VALUES ('Busan', 'BUS');
INSERT INTO Destinations VALUES ('Seoul', 'SEO');
INSERT INTO Destinations VALUES ('Delhi', 'DEL');
INSERT INTO Destinations VALUES ('Kathmandu', 'KTM');
INSERT INTO Destinations VALUES ('Jakarta', 'JAK');
INSERT INTO Destinations VALUES ('Kuala Lumpur', 'KUL');
INSERT INTO Destinations VALUES ('Manila', 'MAN');
INSERT INTO Destinations VALUES ('Singapore', 'SIN');
INSERT INTO Destinations VALUES ('Phuket', 'PHU');
INSERT INTO Destinations VALUES ('Ho Chi Minh City', 'HCM');
INSERT INTO Destinations VALUES ('Jeddah', 'JED');
INSERT INTO Destinations VALUES ('Abu Dhabi', 'ADH');
INSERT INTO Destinations VALUES ('Brussels', 'BRU');
INSERT INTO Destinations VALUES ('Paris', 'PAR');
INSERT INTO Destinations VALUES ('Dublin', 'DUB');
INSERT INTO Destinations VALUES ('Lisbon', 'LIS');
INSERT INTO Destinations VALUES ('Ibiza', 'IBZ');
INSERT INTO Destinations VALUES ('Athens', 'ATH');
INSERT INTO Destinations VALUES ('ROME', 'ROM');
INSERT INTO Destinations VALUES ('Moscow', 'MOS');
INSERT INTO Destinations VALUES ('Helsinki', 'HEL');
INSERT INTO Destinations VALUES ('Mars', 'MRS');


--INSERT INTO Flights VALUES (1, 'Gothenburg', 'London', '2021-06-21', '14:00', 'Boeing 747');
--INSERT INTO Flights VALUES (2, 'Stockholm', 'Berlin', '2021-06-25', '18:00', 'Boeing 747');
--INSERT INTO Flights VALUES (3, 'Copenhagen', 'Frankfurt', '2021-02-28', '11:00', 'Boeing 747');

--INSERT INTO Seats VALUES (1, '1A', false);
--INSERT INTO Seats VALUES (1, '1B', false);
--INSERT INTO Seats VALUES (1, '1C', false);
--INSERT INTO Seats VALUES (1, '1D', false);